DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
	username VARCHAR(50) NOT NULL PRIMARY KEY,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	rolename VARCHAR(24) NOT NULL
);